name: pairk
channels:
  - conda-forge
  - defaults

dependencies:
    # Base depends
  - python>=3.10
  - pip
  - numpy
  - pandas
  - biopython>=1.80
  - seaborn
  - matplotlib
  - importlib-resources
  - pip:
    - alfpy
    - logomaker
    - torch
    - torchvision
    - fair-esm
    - transformers
