name: docs_pairk
channels:
  - conda-forge
  - defaults

dependencies:
    # Base depends
  - python
  - pip
  - sphinx
  - sphinx-rtd-theme
  - sphinx-design
  - sphinx-copybutton
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - pydata-sphinx-theme
  - numpy
  - pandas
  - biopython
    # Pip-only installs
  - pip:
    - -e ../
    - alfpy

