name: docs_pairk
channels:
  - conda-forge
  - defaults

dependencies:
    # Base depends
  - python
  - pip
  - sphinx
  - sphinx-rtd-theme
  - sphinx-design
  - sphinx-copybutton
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - pydata-sphinx-theme
  - nbsphinx
  - numpy<2
  - jupyter
  - pandas
  - biopython
  - importlib-resources
  - seaborn
  - matplotlib
  - numpydoc
    # Pip-only installs
  - pip:
    - -e ../
    - alfpy
    - logomaker
    - torch
    - torchvision
    - fair-esm
    - transformers
    # - sphinxcontrib-pseudocode
